from pathlib import Path


def build_comic_layout(
    outline,
    story,
    image_paths
):
    """
    Build a simple comic layout.

    This version creates a text-based comic layout
    so that the backend can run without errors.
    """

    output_dir = Path("outputs")
    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    output_file = output_dir / "comic_layout.txt"

    lines = []

    lines.append("================================")
    lines.append("        COMICCRAFT AI")
    lines.append("        COMIC STORY")
    lines.append("================================")
    lines.append("")

    # Add outline
    lines.append("STORY OUTLINE")
    lines.append("--------------------------------")

    if isinstance(outline, list):

        for index, panel in enumerate(outline, start=1):

            if isinstance(panel, dict):

                description = panel.get(
                    "scene_description",
                    panel.get("description", "")
                )

                dialogue = panel.get(
                    "dialogue",
                    ""
                )

                lines.append(
                    f"Panel {index}: {description}"
                )

                if dialogue:
                    lines.append(
                        f"Dialogue: {dialogue}"
                    )

            else:

                lines.append(
                    f"Panel {index}: {panel}"
                )

    else:

        lines.append(
            str(outline)
        )

    lines.append("")
    lines.append("STORY")
    lines.append("--------------------------------")
    lines.append(str(story))

    lines.append("")
    lines.append("GENERATED IMAGES")
    lines.append("--------------------------------")

    for image in image_paths:

        lines.append(
            str(image)
        )

    lines.append("")
    lines.append("================================")
    lines.append("Generated by ComicCraft AI")
    lines.append("================================")

    output_file.write_text(
        "\n".join(lines),
        encoding="utf-8"
    )

    return str(output_file)